language: node_js

cache:
  directories:
  - node_modules

node_js:
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
  - "0.12"
  - "0.10"

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - wget https://files.appneta.com/install_appneta.sh
  - sudo sh ./install_appneta.sh f08da708-7f1c-4935-ae2e-122caf1ebe31

before_script:
  - npm install

script: "npm test"
